version: '3.8'

services:
  dev-db:
    image: postgres:latest
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: shop
    volumes:
      - dbdata:/var/lib/postgresql/data

    networks:
      - shop

networks:
  shop:

volumes:
  dbdata: # create the volume for persisting data.
